"""
HTML report generator for SecAudit scan results.
"""

from __future__ import annotations

import datetime
import json
from collections import Counter
from pathlib import Path

from ..core.base_module import ModuleResult, Severity

SEVERITY_ORDER = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]

SEVERITY_STYLES = {
    "CRITICAL": ("#dc2626", "#fee2e2"),
    "HIGH":     ("#ea580c", "#ffedd5"),
    "MEDIUM":   ("#ca8a04", "#fef9c3"),
    "LOW":      ("#2563eb", "#dbeafe"),
    "INFO":     ("#16a34a", "#dcfce7"),
}

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SecAudit Report – {target}</title>
<style>
  :root {{
    --bg: #0f172a; --surface: #1e293b; --surface2: #334155;
    --text: #e2e8f0; --text-muted: #94a3b8; --border: #475569;
    --accent: #38bdf8;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; line-height: 1.6; }}
  .container {{ max-width: 1100px; margin: 0 auto; padding: 2rem; }}
  header {{ border-bottom: 2px solid var(--accent); padding-bottom: 1.5rem; margin-bottom: 2rem; }}
  header h1 {{ font-size: 2rem; color: var(--accent); }}
  header .meta {{ color: var(--text-muted); margin-top: 0.5rem; font-size: 0.9rem; }}
  .summary-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(130px, 1fr)); gap: 1rem; margin-bottom: 2rem; }}
  .summary-card {{ background: var(--surface); border-radius: 0.75rem; padding: 1.25rem; text-align: center; border: 1px solid var(--border); }}
  .summary-card .count {{ font-size: 2.5rem; font-weight: 700; }}
  .summary-card .label {{ color: var(--text-muted); font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; }}
  .module-section {{ margin-bottom: 2rem; }}
  .module-title {{ font-size: 1.2rem; font-weight: 600; color: var(--accent); border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; margin-bottom: 1rem; }}
  .finding {{ background: var(--surface); border-radius: 0.5rem; padding: 1rem 1.25rem; margin-bottom: 0.75rem; border-left: 4px solid; }}
  .finding-header {{ display: flex; justify-content: space-between; align-items: flex-start; gap: 1rem; margin-bottom: 0.5rem; }}
  .finding-title {{ font-weight: 600; font-size: 1rem; }}
  .badge {{ padding: 0.15rem 0.6rem; border-radius: 9999px; font-size: 0.7rem; font-weight: 700; text-transform: uppercase; white-space: nowrap; }}
  .finding-desc {{ color: var(--text-muted); font-size: 0.9rem; margin-bottom: 0.4rem; }}
  .finding-evidence {{ background: var(--surface2); border-radius: 0.25rem; padding: 0.4rem 0.75rem; font-family: 'Courier New', monospace; font-size: 0.82rem; color: #93c5fd; margin: 0.5rem 0; white-space: pre-wrap; word-break: break-all; }}
  .finding-rec {{ font-size: 0.85rem; color: #86efac; margin-top: 0.4rem; }}
  .finding-refs {{ font-size: 0.8rem; margin-top: 0.4rem; }}
  .finding-refs a {{ color: var(--accent); text-decoration: none; }}
  .finding-refs a:hover {{ text-decoration: underline; }}
  .error-box {{ background: #450a0a; border: 1px solid #dc2626; border-radius: 0.5rem; padding: 0.75rem 1rem; color: #fca5a5; font-size: 0.9rem; margin-bottom: 0.75rem; }}
  .metadata-section {{ background: var(--surface); border-radius: 0.5rem; padding: 1rem; margin-bottom: 1rem; font-size: 0.85rem; }}
  .metadata-section pre {{ color: var(--text-muted); white-space: pre-wrap; font-family: monospace; font-size: 0.8rem; overflow-x: auto; }}
  footer {{ text-align: center; color: var(--text-muted); font-size: 0.8rem; margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); }}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>SecAudit Security Report</h1>
    <div class="meta">
      <strong>Target:</strong> {target} &nbsp;|&nbsp;
      <strong>Scan date:</strong> {scan_date} &nbsp;|&nbsp;
      <strong>Modules run:</strong> {module_count}
    </div>
  </header>

  <div class="summary-grid">
    {summary_cards}
  </div>

  {modules_html}

  <footer>
    Generated by <strong>SecAudit Toolkit</strong> &mdash; For authorized use only
  </footer>
</div>
</body>
</html>
"""


class ReportGenerator:
    """Generates an HTML security report from scan results."""

    def __init__(self, results: list[ModuleResult], target: str) -> None:
        self.results = results
        self.target = target
        self.scan_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def _severity_badge(self, severity: str) -> str:
        fg, bg = SEVERITY_STYLES.get(severity, ("#6b7280", "#f3f4f6"))
        return f'<span class="badge" style="background:{bg};color:{fg}">{severity}</span>'

    def _severity_border(self, severity: str) -> str:
        fg, _ = SEVERITY_STYLES.get(severity, ("#6b7280", "#f3f4f6"))
        return fg

    def _render_finding(self, finding) -> str:
        evidence_html = (
            f'<div class="finding-evidence">{finding.evidence}</div>'
            if finding.evidence else ""
        )
        rec_html = (
            f'<div class="finding-rec">&#x1F6A7; <em>{finding.recommendation}</em></div>'
            if finding.recommendation else ""
        )
        refs_html = ""
        if finding.references:
            links = " &bull; ".join(
                f'<a href="{r}" target="_blank">{r}</a>' for r in finding.references
            )
            refs_html = f'<div class="finding-refs">&#x1F517; {links}</div>'

        border_color = self._severity_border(finding.severity.value)
        return f"""
        <div class="finding" style="border-left-color:{border_color}">
          <div class="finding-header">
            <span class="finding-title">{finding.title}</span>
            {self._severity_badge(finding.severity.value)}
          </div>
          <div class="finding-desc">{finding.description}</div>
          {evidence_html}
          {rec_html}
          {refs_html}
        </div>"""

    def _render_module(self, result: ModuleResult) -> str:
        parts = [f'<div class="module-section">']
        parts.append(f'<div class="module-title">&#x1F50D; {result.module_name.replace("_", " ").title()}</div>')

        if result.error:
            parts.append(f'<div class="error-box">&#x26A0; Error: {result.error}</div>')

        # Sort findings by severity
        severity_rank = {s: i for i, s in enumerate(SEVERITY_ORDER)}
        sorted_findings = sorted(result.findings, key=lambda f: severity_rank.get(f.severity, 99))

        for finding in sorted_findings:
            parts.append(self._render_finding(finding))

        if result.metadata:
            meta_str = json.dumps(result.metadata, indent=2, default=str)
            parts.append(f'<details style="margin-top:0.5rem"><summary style="cursor:pointer;color:var(--text-muted);font-size:0.8rem">Raw metadata</summary><div class="metadata-section"><pre>{meta_str}</pre></div></details>')

        parts.append('</div>')
        return "\n".join(parts)

    def _build_summary(self) -> tuple[str, Counter]:
        counter: Counter = Counter()
        for result in self.results:
            for finding in result.findings:
                counter[finding.severity.value] += 1

        cards = []
        for sev in SEVERITY_ORDER:
            count = counter.get(sev.value, 0)
            fg, bg = SEVERITY_STYLES[sev.value]
            cards.append(f"""
            <div class="summary-card" style="border-color:{fg}">
              <div class="count" style="color:{fg}">{count}</div>
              <div class="label">{sev.value}</div>
            </div>""")

        total = sum(counter.values())
        cards.append(f"""
        <div class="summary-card">
          <div class="count">{total}</div>
          <div class="label">Total</div>
        </div>""")

        return "\n".join(cards), counter

    def generate(self, output_path: Path) -> Path:
        summary_cards, _ = self._build_summary()
        modules_html = "\n".join(self._render_module(r) for r in self.results)

        html = HTML_TEMPLATE.format(
            target=self.target,
            scan_date=self.scan_date,
            module_count=len(self.results),
            summary_cards=summary_cards,
            modules_html=modules_html,
        )

        output_path.write_text(html, encoding="utf-8")
        return output_path

    def generate_json(self, output_path: Path) -> Path:
        data = {
            "target": self.target,
            "scan_date": self.scan_date,
            "results": [r.to_dict() for r in self.results],
        }
        output_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        return output_path
